### ISSUE TITLE
Práctica 1

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipopromastergamer777#2]

**Comment by FedericoVictorianoSierra** [comment]
[Practica 1 Ingeneria de Software (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipopromastergamer777/files/10806770/Practica.1.Ingeneria.de.Software.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Practica 1 Ingeneria de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipopromastergamer777/files/10809907/Practica.1.Ingeneria.de.Software.pdf)

**Comment by JoseABCruz** [comment]
[Practica 1 Ingeneria de Software (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipopromastergamer777/files/10809948/Practica.1.Ingeneria.de.Software.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by SANDRAVELASCO** [comment]
[Practica 1 Ingeneria de Software (Sandra Gabriela Velasco Guzmán).pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipopromastergamer777/files/10809997/Practica.1.Ingeneria.de.Software.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by mel-16** [comment]
17.4% 
PORTADA 25
PROCEDIMIENTO 25
FIGURAS 15 
CONCLUSION 22

**Comment by josealfredo79** [comment]
Bien hecho y revisado
